### PR TITLE
controller & notify events queue code improvements

### PR DESCRIPTION
**Pull request by wulf7**
1. fix signal handling issue https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=204366
2. Some controller fixes and improvements. Stress test is not included as it is unportable now :-(
3. inotify events queue code is completed so https://github.com/idea4bsd/fsnotifier/issues/1 is fixed

### CODE REVIEW

**Comment by wulf7** [comment]
Hmmm. Some development code leaked (last 3 commits). So I overwrote it with up to date versions with forced push to not spoil the commit history

**Comment by dmatveev** [comment]
So many changes, thanks Vladimir, will definitely merge it soon!

**Comment by wulf7** [comment]
Hi, Dmitry.
A there any news on these changes?
Given the fact that bugfixes for 2 critical bugs affecting at least users of inotifywatch and intelijdea are not even reviewed within 2 month I consider this project to be unsupported. And I`m really tired of your inability to support this so it would better if you would just write that "you can`t do it" somewhere on your page to not confuse people using the project
I`am also have private life and very busy on BSD-unrelated work and nobody pays me for libinotify so I have to spent my priceless free time trying to develop and support it and I'm not fond of the fact that my efforts go to the thrash can.
I`m very sorry if my words insults you but I think now is the time to do something with a current state of things.

**Comment by dmatveev** [comment]
Hi Vladimir,

Sorry for a delay. Your efforts will never go to the thrash can! 

Here is what I can do. Please push all your work here: https://github.com/libinotify-kqueue/libinotify-kqueue

I will put a notice in my repository that it is not "official" anymore.

Dmitry

**Comment by wulf7** [comment]
Thank you. I have pushed master branch here

**Comment by wulf7** [comment]
master repository has been moved to https://github.com/libinotify-kqueue/libinotify-kqueue

**Pull request closed without merging**
